#
# GNUmakefile for target NFSManager
# begin - generated by buildtool, please don't modify
#

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = NFSManager

NFSManager_OBJC_FILES = NFSManager/main.m \
	NFSManager/NFSImportParameters.m \
	NFSManager/AppDelegate.m \
	NFSManager/ImportsController.m \
	NFSManager/ExportsController.m 

NFSManager_RESOURCE_FILES = NFSManager/Assets.xcassets \
	NFSManager/Base.lproj/MainMenu.xib \
	NFSManager/Assets.xcassets/AppIcon.appiconset/nfs_manager32\ 1.png \
	NFSManagerInfo.plist 

ADDITIONAL_INCLUDE_DIRS += -I. \
	-I./NFSManager 

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/common.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble

#
# end - generated makefile
#
